### ISSUE TITLE
Style fixes

### ISSUE THREAD

**Issue by zimokk** [803142/codejam-virtual-keyboard#3]
https://github.com/803142/codejam-virtual-keyboard/blob/5897be7cef328c020c2e6fe48b3d0c25f9978074/src/style.scss#L17

1) Please unite border styles like : "border: 4px dotted blue;" instead of 3-4 separate styles
2) Remove styles word-spacing, letter-spacing with values because default values "normal" anyway

**Comment by 803142** [comment]
https://github.com/803142/codejam-virtual-keyboard/pull/1/commits/9f96a69b9af5ba7b54321e555e3a831525070c2d
1.Border styles has been rewrited
2. Unnecessary styles remooved.
